title: "magpie"
subtitle: "homelab"

header: false
footer: ""

columns: "3"
connectivityCheck: false

theme: "default"

stylesheet:
  - "assets/custom.css"

links:
  - name: "source"
    icon: "fab fa-git-alt"
    url: "https://github.com/tlgs/magpie"

services:
  - name: "apps"
    icon: "fas fa-cubes"
    items:
      - name: "Navidrome"
        subtitle: "Music streaming server"
        url: "http://navidrome.magpie.local"
        logo: "https://github.com/NX211/homer-icons/raw/master/png/navidrome.png"

  - name: "network"
    icon: "fas fa-network-wired"
    items:
      - name: "TP-Link Archer C7"
        subtitle: "Router and Network Gateway"
        url: "http://tplinkwifi.net"
        logo: "https://github.com/NX211/homer-icons/raw/master/png/tplink.png"

      - name: "Pi-hole"
        subtitle: "DNS sinkhole"
        url: "http://pihole.magpie.local"
        logo: "https://github.com/NX211/homer-icons/raw/master/png/pihole.png"

  - name: "meta"
    icon: "fas fa-cogs"
    items:
      - name: "Traefik"
        subtitle: "Reverse proxy"
        url: "http://traefik.magpie.local"
        logo: "https://github.com/NX211/homer-icons/raw/master/png/traefik.png"

      - name: "Portainer"
        subtitle: "Docker GUI management"
        url: "http://portainer.magpie.local"
        logo: "https://github.com/NX211/homer-icons/raw/master/png/portainer.png"

      - name: "cAdvisor"
        subtitle: "Container metrics aggregator"
        url: "http://cadvisor.magpie.local"
        logo: "https://github.com/NX211/homer-icons/raw/master/png/cadvisor.png"
