version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:2021.09
    depends_on:
      - unbound
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.pihole.rule=Host(`pihole.magpie.local`)"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
    hostname: mag-pihole
    environment:
      TZ: Europe/Dublin
      ServerIP: 192.168.0.69
      PIHOLE_DNS_: 172.20.0.53#5335;172.20.0.53#5335
      DNSMASQ_LISTENING: all
    dns:
      - 127.0.0.1
      - 172.20.0.53
    volumes:
      - "/home/pi/pihole/etc-pihole/:/etc/pihole/"
      - "/home/pi/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/"
      - "/home/pi/pihole/var-log/pihole.log:/var/log/pihole.log"
      - "./lighttpd-external.conf:/etc/lighttpd/external.conf"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8084:80/tcp"
    networks:
      traefik:
      dns_net:
        ipv4_address: 172.20.0.100
    restart: unless-stopped

  unbound:
    container_name: unbound
    image: mvance/unbound-rpi:1.13.1
    ports:
      - "5335:5335/tcp"
      - "5335:5335/udp"
    volumes:
      - "./unbound.conf:/opt/unbound/etc/unbound/unbound.conf:ro"
    networks:
       dns_net:
         ipv4_address: 172.20.0.53
    healthcheck:
      test: ["CMD", "drill", "@127.0.0.1", "-p", "5335", "cloudflare.com", "||", "exit", "1"]
      interval: 5s
      timeout: 3s
      start_period: 5s
    restart: unless-stopped

networks:
  dns_net:
    name: dns_net
    ipam:
      config:
        - subnet: 172.20.0.0/16
  traefik:
    external: true
