version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole
    depends_on:
      - dhcp-helper
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pihole.rule=Host(`pihole.magpie.local`)"
      - "traefik.http.routers.pihole.entrypoints=web"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
    hostname: mag-pihole
    cap_add:
      - NET_ADMIN
    environment:
      TZ: Europe/Dublin
      PIHOLE_DNS_: 1.1.1.1;1.0.0.1
      ServerIP: 192.168.0.69
      DNSMASQ_LISTENING: all
      DHCP_ACTIVE: "true"
      DHCP_START: 192.168.0.100
      DHCP_END: 192.168.0.249
      DHCP_ROUTER: 192.168.0.1
      DHCP_LEASETIME: 2
      PIHOLE_DOMAIN: none
      VIRTUAL_HOST: pihole.magpie.local
      VIRTUAL_PORT: 80
    dns:
      - 127.0.0.1
      - 1.1.1.1
    volumes:
      - "/home/pi/pihole/etc-pihole/:/etc/pihole/"
      - "/home/pi/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/"
      - "/home/pi/pihole/var-log/pihole.log:/var/log/pihole.log"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8083:80/tcp"
    networks:
      traefik:
      dhcp_relay:
        ipv4_address: 172.31.0.100
    restart: unless-stopped

  dhcp-helper:
    container_name: dhcp-helper
    build: ./dhcp-helper
    image: dhcp-helper
    command: -s 172.31.0.100
    cap_add:
      - NET_ADMIN
    network_mode: host
    restart: unless-stopped

networks:
  dhcp_relay:
    name: dhcp_relay
    ipam:
      config:
        - subnet: 172.31.0.0/16
  traefik:
    external: true
