version: "3"

services:
  airsonic:
    container_name: airsonic
    image: airsonicadvanced/airsonic-advanced:edge-11.0.0-SNAPSHOT.20210908073208
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.airsonic.rule=Host(`airsonic.magpie.local`)"
      - "traefik.http.services.airsonic.loadbalancer.server.port=4040"
    environment:
      PUID: 1000
      PGID: 1000
      TZ: ${TZ}
    volumes:
      - "${HOME}/airsonic/data:/var/airsonic"
      - "${HOME}/airsonic/music:/var/music"
      - "${HOME}/airsonic/playlists:/var/playlists"
      - "${HOME}/airsonic/podcasts:/var/podcasts"
    ports:
      - "4040:4040"
    networks:
      - traefik_net
    restart: unless-stopped

  nfs-server:
    container_name: nfs-server
    build: ./nfs-server
    image: nfs-server
    cap_add:
      - SYS_ADMIN
      - SYS_MODULE
    environment:
      NFS_DISABLE_VERSION_3: 1
    volumes:
      - "/lib/modules:/lib/modules:ro"
      - "./nfs-exports.txt:/etc/exports:ro"
      - "${HOME}/airsonic/music:/music"
    ports:
      - 2049:2049
    networks:
      - traefik_net
    restart: unless-stopped

networks:
  traefik_net:
    external: true
