version: "3"

services:
  airsonic:
    image: airsonicadvanced/airsonic-advanced
    container_name: airsonic
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.airsonic.rule=Host(`airsonic.magpie.local`)"
      - "traefik.http.services.airsonic.loadbalancer.server.port=4040"
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Dublin
    volumes:
      - "/home/pi/airsonic/data:/var/airsonic"
      - "/home/pi/airsonic/music:/var/music"
      - "/home/pi/airsonic/playlists:/var/playlists"
      - "/home/pi/airsonic/podcasts:/var/podcasts"
    ports:
      - "4040:4040"
    networks:
      - traefik
    restart: unless-stopped

networks:
  traefik:
    external: true
