#!/bin/bash
#
# Fetches and decompresses a DietPi image into the current directory.
#
# Usage
# -----
# ./get-dietpi MODEL

case $1 in
  nanopineo)
    img_url='https://dietpi.com/downloads/images/DietPi_NanoPiNEO-ARMv7-Bullseye.7z'
    ;;
  rpi4b)
    img_url='https://dietpi.com/downloads/images/DietPi_RPi-ARMv8-Bullseye.7z'
    ;;
  '')
    printf 'no model provided\n' >&2
    ;;&
  ?*)
    printf 'bad model: %s\n' "$1" >&2
    ;;&
  *)
    printf 'possible options are {nanopineo,rpi4b}\n' >&2
    exit 1
    ;;
esac

archive_file=$(basename $img_url)
img_file="${archive_file%.*}.img"

if [[ -f "$img_file" ]]; then
  echo 'nothing to do'
  exit
fi

unset tmpdir
trap '[[ $tmpdir ]] && rm -rf "$tmpdir"' EXIT
tmpdir=$(mktemp -d)

pushd "$tmpdir" >/dev/null || exit 1
curl -O "$img_url"
7z x "$archive_file"
popd >/dev/null || exit 1

cp "$tmpdir/$img_file" .
