#!/bin/bash
#
# Patches a DietPi image with a couple of configuration settings:
#
#   - Set custom hostname and static ip address
#   - Use Cloudflare's DNS servers
#   - Use OpenSSH as the SSH server
#     (Dropbear does not include utilities required to integrate with Ansible)
#   - Install Python
#   - Opt out of DietPi's survey
#   - Disable serial console
#
# Notes
# -----
# Requires `jc` and `jq`, and the user running it should be able
# to elevate privileges (sudo).
#
# Usage
# -----
# ./patch-dietpi IMAGE_FILE HOSTNAME STATIC_IP

die() {
  printf '%s\n' "$1" >&2
  exit 1
}

unset tmpdir
trap '[[ $tmpdir ]] && rm -rf "$tmpdir"' EXIT
tmpdir=$(mktemp -d)

mntdir="$tmpdir/mnt"
mkdir -p "$mntdir"

read -r offset n_partitions <<<"$(
  jc sfdisk -l "$1" \
    | jq -r '
        [
          .[0].partitions[0].start * .[0].logical_sector_size,
          .[0].partitions | length
        ]
        | join(" ")
      '
)"

trap 'sudo umount "$mntdir"' EXIT
sudo mount -o loop,offset="$offset" "$1" "$mntdir" || exit 1

if [[ "$n_partitions" == 1 ]]; then
  infile="$mntdir/boot/dietpi.txt"
else
  infile="$mntdir/dietpi.txt"
fi

if [[ -f "$infile.bak" ]]; then
  echo 'image file seems to have been patched already'
  exit
fi

outfile="$tmpdir/patched-dietpi.txt"
while IFS= read -r line; do
  case "$line" in
    AUTO_SETUP_NET_USESTATIC=*) echo 'AUTO_SETUP_NET_USESTATIC=1' ;;
    AUTO_SETUP_NET_STATIC_IP=*) echo "AUTO_SETUP_NET_STATIC_IP=$3" ;;
    AUTO_SETUP_NET_STATIC_DNS=*) echo 'AUTO_SETUP_NET_STATIC_DNS=1.1.1.1 1.0.0.1' ;;
    AUTO_SETUP_NET_HOSTNAME=*) echo "AUTO_SETUP_NET_HOSTNAME=$2" ;;
    AUTO_SETUP_HEADLESS=*) echo "AUTO_SETUP_HEADLESS=1" ;;
    AUTO_SETUP_SSH_SERVER_INDEX=*) echo 'AUTO_SETUP_SSH_SERVER_INDEX=-2' ;;
    AUTO_SETUP_AUTOMATED=*) echo 'AUTO_SETUP_AUTOMATED=1' ;;
    \#AUTO_SETUP_INSTALL_SOFTWARE_ID=*) echo 'AUTO_SETUP_INSTALL_SOFTWARE_ID=130' ;;
    SURVEY_OPTED_IN=*) echo 'SURVEY_OPTED_IN=0' ;;
    CONFIG_SERIAL_CONSOLE_ENABLE=*) echo 'CONFIG_SERIAL_CONSOLE_ENABLE=0' ;;
    *) echo "$line" ;;
  esac
done <"$infile" >"$outfile"

sudo cp "$infile" "$infile.bak" && sudo mv "$outfile" "$infile"
