name: ci
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container: hadolint/hadolint:latest-debian
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Run hadolint on Dockerfiles
        run: find . -name Dockerfile | xargs hadolint
        shell: bash
